name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Build with Gradle
        run: ./gradlew shadowJar --no-daemon

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FireFlow
          path: ./build/libs/FireFlow-*-all.jar


      - name: Generate Wiki
        id: build
        run: java -cp ./build/libs/FireFlow-*-all.jar de.blazemcworld.fireflow.WikiGenerator

      - name: Upload Wiki Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: wiki/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4